# Generated by Django 4.2 on 2023-04-06 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор пользователя')),
                ('person_last_name', models.CharField(max_length=512, verbose_name='Фамилия')),
                ('person_firs_name', models.CharField(max_length=512, verbose_name='Имя')),
                ('person_sec_name', models.CharField(max_length=512, verbose_name='Отчество')),
                ('person_login', models.CharField(max_length=512, verbose_name='Логин')),
                ('person_password', models.CharField(max_length=512, verbose_name='Пароль')),
                ('person_is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRoles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор роли')),
                ('role_name', models.CharField(max_length=512, verbose_name='Название роли')),
                ('role_code', models.CharField(max_length=512, verbose_name='Код роли')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор тэга')),
                ('tag_name', models.CharField(max_length=512, verbose_name='Название тэга')),
                ('tag_code', models.CharField(max_length=512, verbose_name='Код тэга')),
            ],
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('task_state_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор состояния задачи')),
                ('task_state_name', models.CharField(max_length=512, verbose_name='Наименование состояния задачи')),
                ('task_state_code', models.CharField(max_length=10, verbose_name='Код состояния задачи')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 6, 16, 51, 23, 610125, tzinfo=datetime.timezone.utc), verbose_name='Дата создания задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_text',
            field=models.TextField(default='qwer', verbose_name='Текст задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(default='qqwer', max_length=512, verbose_name='Заголовок задачи'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskUserRoles',
            fields=[
                ('task_user_link_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор связи')),
                ('task_user_link_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.personroles')),
                ('task_user_link_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.task')),
                ('task_user_link_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.person')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTags',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор связи')),
                ('link_tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.tag')),
                ('link_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.task')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор комментария')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')),
                ('comment_autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TaskManager.person')),
                ('comment_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_state_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='TaskManager.taskstate'),
            preserve_default=False,
        ),
    ]
