# Generated by Django 4.2 on 2023-04-06 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_person_personroles_tag_taskstate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskuserroles',
            name='task_user_link_role_id',
        ),
        migrations.RemoveField(
            model_name='taskuserroles',
            name='task_user_link_task_id',
        ),
        migrations.RemoveField(
            model_name='taskuserroles',
            name='task_user_link_user_id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='TaskManager.person'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_executer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executer', to='TaskManager.person'),
        ),
        migrations.DeleteModel(
            name='PersonRoles',
        ),
        migrations.DeleteModel(
            name='TaskUserRoles',
        ),
    ]
