# Generated by Django 4.2 on 2023-04-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_remove_taskuserroles_task_user_link_role_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_executer',
        ),
        migrations.AddField(
            model_name='task',
            name='task_executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_task_executor', to='TaskManager.person'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_comment_author', to='TaskManager.person'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_comment_task', to='TaskManager.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_task_author', to='TaskManager.person'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_task_state', to='TaskManager.taskstate'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_task_type', to='TaskManager.tasktype'),
        ),
        migrations.AlterField(
            model_name='tasktags',
            name='link_tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_link_tag_tag', to='TaskManager.tag'),
        ),
        migrations.AlterField(
            model_name='tasktags',
            name='link_task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_link_tag_task', to='TaskManager.task'),
        ),
    ]
